/* Design preview only. Events below simulate state changes; no GPS, login, storage or reports are sent. */
const params=new URLSearchParams(location.search); let screen=params.get('screen')||'success';let region='전체';let selected=0;
const regions=['전체','수도권','강원','충청','전라','경상','제주'];
// Representative design fixtures, not the production 96-mountain database. Counts follow the supplied brief.
const mountains=[
['북한산',836,'수도권',true,'autumn','2026.09.05'],['도봉산',740,'수도권',true,'summer','2026.08.22'],['관악산',632,'수도권',true,'spring','2026.05.16'],['수락산',638,'수도권'],['소요산',587,'수도권'],['감악산',675,'수도권'],['명지산',1267,'수도권'],['운악산',935,'수도권'],['화악산',1468,'수도권'],['축령산',879,'수도권'],['용문산',1157,'수도권'],['유명산',862,'수도권'],['천마산',812,'수도권'],['마니산',472,'수도권'],
['설악산',1708,'강원',true,'winter','2026.02.14'],['오대산',1563,'강원',true,'summer','2026.07.18'],['치악산',1288,'강원'],['계룡산',845,'충청',true,'spring','2026.04.11'],['속리산',1058,'충청'],['월악산',1097,'충청'],['내장산',763,'전라'],['덕유산',1614,'전라'],['월출산',809,'전라'],['지리산(통영)',398,'경상'],['남해 금산',681,'경상'],['가야산',1430,'경상'],['한라산',1947,'제주',true,'winter','2026.01.24']
].map((v,i)=>({id:i,name:v[0],height:v[1],region:v[2],collected:!!v[3],season:v[4]||'autumn',date:v[5]||'',seed:i}));
const counts={'수도권':[3,14],'강원':[2,22],'충청':[1,12],'전라':[0,18],'경상':[0,28],'제주':[1,2]};
const root=document.getElementById('app');
function stamp(m,size=76,override){return stampSVG({...m,collected:override??m.collected,size,label:m.name});}
function btn(label,action,kind='',extra=''){return `<button class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;}
function footer(html,cl=''){return `<footer class="bottom-actions ${cl}">${html}</footer>`;}
function tabs(which){return `<nav class="tabbar" aria-label="하단 탭">${['home','collection'].map((v,i)=>`<button class="tab ${which===v?'active':''}" data-go="${v}" ${which===v?'aria-current="page"':''}>${icon(i?'collection':'home')}<span>${i?'내 스탬프':'홈'}</span></button>`).join('')}</nav>`;}
function head(title,sub){return `<div class="page-head"><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>`;}
function setScreen(s){screen=s;const url=new URL(location.href);url.searchParams.set('screen',s);history.pushState({s},'',url);render();window.scrollTo(0,0);}
function goDetails(id){selected=+id;setScreen('detail');}
function render(){let m=mountains[selected];let html='';
if(['success','save-error'].includes(screen)){
html=`<section class="page success"><div class="success-heading"><h1>스탬프를 획득했어요</h1><p>정상에 도착한 걸 확인했어요.</p></div><article class="ticket"><div class="ticket-main"><div class="stamp-impact">${stamp(m,160,true)}</div><h2>${m.name}</h2><p class="altitude">${m.height.toLocaleString()}m${m.id===0?' · 백운대':''}</p><p class="ticket-date">2026.09.05</p></div><div class="ticket-stub"><span class="seal-check">${icon('check',22)}</span><div><strong>내 스탬프</strong><p>96곳 중 7곳을 모았어요</p></div></div></article>${screen==='save-error'?'<div class="save-alert" role="status"><strong>스탬프를 저장하지 못했어요</strong><p>인터넷 연결을 확인한 뒤 다시 저장해 주세요.</p></div>':''}${footer(btn(screen==='save-error'?'다시 저장':'내 스탬프',screen==='save-error'?'save':'collection'))}</section>`;
}else if(['collection','collection-empty'].includes(screen)){
let empty=screen==='collection-empty';html=`<section class="page"><div class="collection-head"><h1>내 스탬프</h1><p>96곳 중 ${empty?'0':'7'}곳을 모았어요</p><div class="progress" role="progressbar" aria-label="모은 스탬프" aria-valuenow="${empty?0:7}" aria-valuemin="0" aria-valuemax="96"><span style="width:${empty?0:7/96*100}%"></span></div>${empty?'<div class="empty-intro">정상에 도착해서 인증하면 여기 빈 자리가 하나씩 채워져요.</div>':''}</div><div class="collection-main">${regions.slice(1).map(r=>`<section class="region"><div class="section-title"><h3>${r}</h3><span>${empty?0:counts[r][0]} / ${counts[r][1]}</span></div><div class="grid">${mountains.filter(m=>m.region===r).map(m=>`<button class="stamp-cell ${m.collected&&!empty?'is-collected':''}" data-mountain="${m.id}">${stamp(m,76,empty?false:m.collected)}<strong>${m.name}</strong><span class="caption">${m.collected&&!empty?m.date:m.height.toLocaleString()+'m'}</span></button>`).join('')}</div></section>`).join('')}</div>${tabs('collection')}</section>`;
}else if(['home','home-denied','home-loading','home-error'].includes(screen)){
let denied=screen==='home-denied';html=`<section class="page">${head('오늘 정상','가까운 산부터 보여드려요')}${denied?`<aside class="notice">${icon('location',28)}<p>위치를 허용하면 가까운 산부터 보여드려요. 아래 버튼을 누르면 권한을 다시 물어봐요.</p>${btn('위치 허용하기','allow-home','outline')}</aside>`:`<div class="list-progress">${icon('collection',24)}<p>96곳 중 7곳을 모았어요</p></div>`}<div class="chips" role="group" aria-label="권역">${regions.map(r=>`<button class="chip ${r===region?'selected':''}" data-region="${r}" aria-pressed="${r===region}">${r}</button>`).join('')}</div>${screen==='home-loading'?'<div class="loading-list" role="status"><p class="small muted" style="margin-bottom:16px">산 목록을 불러오고 있어요</p>'+Array(5).fill('<div class="skeleton" aria-hidden="true"></div>').join('')+'</div>':screen==='home-error'?`<div class="notice"><p>산 목록을 불러오지 못했어요</p>${btn('다시 시도','reload','outline')}</div>`:`<div class="list">${mountains.filter(m=>region==='전체'||m.region===region).map((m,i)=>`<button class="mountain-row" data-mountain="${m.id}">${stamp(m,40)}<div class="row-copy"><strong>${m.name}</strong><p>${m.height.toLocaleString()}m${denied?'':` · ${(3.2+i*2.7).toFixed(1)}km`}</p></div><div class="row-end">${m.collected?'<span class="badge">모음</span>':''}${icon('chevron',18)}</div></button>`).join('')}</div>`}${tabs('home')}</section>`;
}else if(['detail','detail-collected','checking','hiking'].includes(screen)){
let got=screen==='detail-collected';html=`<section class="page detail"><div class="hero">${stamp(m,160,got)}</div><div class="detail-info"><h1>${m.name}</h1><p>높이 ${m.height.toLocaleString()}m${m.id===0?' · 인증 지점 백운대':''}</p>${got?'<span class="badge">'+icon('check',16)+'이 산의 스탬프를 모았어요</span>':''}</div><div class="stats"><p>${icon('people',20)}지금 3명 등산 중</p><p>${icon('flag',20)}오늘 5명이 정상을 찍었어요</p><p>${icon('collection',20)}지금까지 128명 인증</p></div>${footer(btn(screen==='hiking'?'산행을 시작했어요':'산행 시작','hike','secondary',screen==='hiking'?'disabled':'')+btn(screen==='checking'?'<span class="spinner"></span>위치를 확인하고 있어요':'정상 인증하기','verify','',screen==='checking'?'disabled':''),'two')}</section>`;
}else if(['login','login-loading','login-error'].includes(screen)){
html=`<section class="page intro"><div class="content"><h1 class="brand-title">오늘 정상</h1><p class="intro-sub">100대 명산 정상 스탬프</p><div class="hero-mark">${stamp(m,160,true)}</div><div class="state-copy" role="status">${screen==='login-error'?'<strong>로그인이 완료되지 않았어요</strong>아래 버튼을 눌러 다시 시도해 주세요.':screen==='login-loading'?'로그인하고 있어요':''}</div></div>${footer(btn(screen==='login-loading'?'<span class="spinner"></span>로그인하고 있어요':'토스로 로그인하기','login','',screen==='login-loading'?'disabled':''))}</section>`;
}else if(screen==='report'){
html=`<section class="page"><form id="report-form" style="display:flex;flex-direction:column;flex:1" novalidate><div class="form-content"><label for="peak">지금 계신 봉우리 이름을 알려주세요</label><input id="peak" name="peak" placeholder="예: 문수봉" maxlength="20" autocomplete="off" required aria-describedby="count privacy form-error"><p class="count" id="count">0 / 20</p><p class="form-error" id="form-error" role="status"></p><p class="privacy" id="privacy">이름과 지금 위치만 보내요. 다른 사람에게는 보이지 않고, 정상 좌표를 고칠지 판단하는 데만 써요. 개인정보는 적지 말아주세요.</p></div>${footer('<button class="btn" type="submit">보내기</button>')}</form></section>`;
}else if(screen==='report-done'){
html=`<section class="page permission"><div class="content"><div class="state-icon">${icon('check',36)}</div><h1>알려주셔서 고마워요.<br>확인해서 반영할게요.</h1></div>${footer(btn('홈','home'))}</section>`;
}else if(screen==='permission'){
html=`<section class="page permission"><div class="content"><div class="state-icon">${icon('location',36)}</div><h1>위치 권한이 필요해요</h1><p>아래 버튼을 눌러 위치를 다시 확인해 주세요.</p></div>${footer(btn('위치 허용하기','allow-detail'))}</section>`;
}else if(screen==='components'){
html=`<section class="sample-sheet"><h1>스탬프</h1><p class="small muted" style="margin-top:8px">모음 / 미모음</p>${[40,76,160].map(size=>`<div class="size-row">${stamp(m,size,true)}${stamp(m,size,false)}${size<160?`<span class="sample-meta">${size}px</span>`:''}</div>`).join('')}<p class="caption muted">상세·성공 160px</p><h2>계절</h2><div class="season-grid">${Object.entries({spring:'봄',summer:'여름',autumn:'가을',winter:'겨울'}).map(([s,n])=>`<div class="season-item">${stamp({...m,season:s},76,true)}<span>${n}</span></div>`).join('')}</div><h2>고도</h2><div class="season-grid">${[450,836,1267,1708].map((height,i)=>`<div class="season-item">${stamp({...m,height,seed:i},76,true)}<span>${height}m</span></div>`).join('')}</div></section>`;
}else{
const errors={'fail':'정상까지 850m','accuracy':'위치 정확도가 낮아요','altitude':'고도가 정상과 달라요','stale':'위치 정보가 오래됐어요','duplicate':'오늘 스탬프는 이미 받았어요','unavailable':'위치를 확인할 수 없어요'};
html=`<section class="page result-page"><article class="result-card"><div class="state-icon">${icon('location',36)}</div><h1>${errors[screen]||errors.fail}</h1>${screen==='fail'?'<p>정상에 도착한 뒤 다시 눌러주세요.</p>':''}</article><div class="report-action">${btn('여기도 북한산 정상이에요','report','ghost')}</div>${footer(btn('정상 인증하기','verify'))}</section>`;
}
root.innerHTML=html;document.title='오늘 정상 · '+screen;
root.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>setScreen(el.dataset.go));root.querySelectorAll('[data-mountain]').forEach(el=>el.onclick=()=>goDetails(el.dataset.mountain));root.querySelectorAll('[data-region]').forEach(el=>el.onclick=()=>{region=el.dataset.region;render()});root.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>act(el.dataset.action));
const input=document.getElementById('peak');if(input){input.oninput=()=>{document.getElementById('count').textContent=input.value.length+' / 20';document.getElementById('form-error').textContent='';};document.getElementById('report-form').onsubmit=e=>{e.preventDefault();if(!input.value.trim()){document.getElementById('form-error').textContent='봉우리 이름을 입력해 주세요.';input.setAttribute('aria-invalid','true');input.focus();return;}setScreen('report-done');};}
}
function act(a){if(a==='verify'){setScreen('checking');setTimeout(()=>{if(screen==='checking')setScreen('success')},800)}else if(a==='login'){setScreen('login-loading');setTimeout(()=>{if(screen==='login-loading')setScreen('home')},800)}else if(a==='save'){setScreen('success')}else if(a==='allow-home'||a==='reload'){setScreen('home')}else if(a==='allow-detail'){setScreen('detail')}else if(a==='hike'){setScreen('hiking')}else setScreen(a);}
window.onpopstate=()=>{screen=new URLSearchParams(location.search).get('screen')||'success';render()};render();
